## Indexing and Selections

Indexing and selection in Pandas refer to the process of accessing specific rows, columns, or elements from a DataFrame or Series. Pandas provides various methods for indexing and selection, allowing you to extract the data you need for analysis and manipulation. Here are the main techniques for indexing and selection in Pandas:

**Indexing and Selection in DataFrame:**

1. **Bracket `[]` Operator:**
   - Selecting a Single Column: `df['column_name']` or `df.column_name`
   - Selecting Multiple Columns: `df[['col1', 'col2']]`

2. **`.loc[]` Operator:**
   - Selection by Label (Row and Column): `df.loc[row_label, column_label]`
   - Slicing Rows: `df.loc[start_row:end_row]`
   - Selecting Rows and Columns: `df.loc[row_labels, column_labels]`

3. **`.iloc[]` Operator:**
   - Selection by Integer Position (Row and Column): `df.iloc[row_index, col_index]`
   - Slicing Rows: `df.iloc[start_row:end_row]`
   - Selecting Rows and Columns: `df.iloc[row_indices, col_indices]`

4. **Boolean Indexing:**
   - Selecting Rows Based on Condition: `df[df['column'] > value]`
   - Combining Conditions: `df[(df['col1'] > value1) & (df['col2'] < value2)]`

5. **`.at[]` and `.iat[]`:**
   - Fast scalar value access by label or integer position: `df.at[row_label, column_label]` or `df.iat[row_index, col_index]`

**Indexing and Selection in Series:**

1. **Bracket `[]` Operator:**
   - Selecting by Label: `series[label]`
   - Selecting by Integer Position: `series[position]`
   - Selecting Multiple Elements: `series[start:end]`

2. **`.loc[]` Operator:**
   - Selection by Label: `series.loc[label]`
   - Slicing: `series.loc[start:end]`

3. **`.iloc[]` Operator:**
   - Selection by Integer Position: `series.iloc[position]`
   - Slicing: `series.iloc[start:end]`

4. **Boolean Indexing:**
   - Selecting Elements Based on Condition: `series[series > value]`

These indexing and selection methods allow you to retrieve specific data from a DataFrame or Series based on your needs. The selection techniques are flexible and powerful, making data extraction and analysis in Pandas efficient and intuitive. Remember that proper indexing and selection are essential for efficient data manipulation and analysis in Pandas.

In [1]:
import pandas as pd

In [2]:
df_ext = pd.read_csv("data/nba.csv") # Load the dataset
df_ext.head() # Display the first few rows of the DataFrame

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

**Bracket `[]` Operator**

In [3]:
#single column
salary_series = df_ext['Salary'] # Select the 'Salary' column using bracket notation
salary_series

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, Length: 458, dtype: float64

In [4]:
#single column
salary_series = pd.DataFrame(df_ext['Salary']) # Select the 'Salary' column using bracket notation and convert to DataFrame
salary_series

        Salary
0    7730337.0
1    6796117.0
2          NaN
3    1148640.0
4    5000000.0
..         ...
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN

[458 rows x 1 columns]

In [5]:
#multiple columns
name_team_df = df_ext[["Name", "Salary"]] # Select 'Name' and 'Salary' columns
name_team_df.head(3)   # Display the first 3 rows of the selected columns

            Name     Salary
0  Avery Bradley  7730337.0
1    Jae Crowder  6796117.0
2   John Holland        NaN

**`.loc[]` operator**

In [6]:
#get salary for Name =  Avery Bradley
df_ext_name_salary = df_ext.loc[0, "Salary"] # Access the 'Salary' for the first row (Avery Bradley)
df_ext_name_salary

np.float64(7730337.0)

In [7]:
df_ext.columns # View the column names of the NBA DataFrame

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [8]:
#get College and Salary for alternate Names upto index = 10
df_ext_name_salary = df_ext.loc[0:10:2, "College":"Salary"] # Access 'College' to 'Salary' for every second row from index 0 to 10
df_ext_name_salary

              College     Salary
0               Texas  7730337.0
2   Boston University        NaN
4                 NaN  5000000.0
6                 LSU  1170960.0
8          Louisville  1824360.0
10         Ohio State  2569260.0

**`.iloc[]` Operator**

In [9]:
df_ext.head() # View the first few rows of the DataFrame

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [10]:
#get entry at 4th row and 5th column
result = df_ext.iloc[4, 5]  # Access the entry at the 4th row and 5th column using integer-location based indexing
result

'6-10'

## Boolean Indexing

Boolean indexing, often called Boolean Masking, is a flexible method for selecting data in Pandas DataFrames and Series.

It allows you to select subsets of data based on whether the data meets one or more specified logical conditions.

**The Core Concept: The Boolean Series (The Mask)**

The process starts by creating a Boolean Series (a Pandas Series composed entirely of True and False values). 
This Series is your "mask."

You define a logical condition (e.g., df['Age'] > 30).

Pandas evaluates this condition for every row in the DataFrame.

The result is a new Series where:

True indicates the row meets the condition.

False indicates the row does not meet the condition.

In [11]:
#get all the players where age > 28
mask = df_ext["Age"] > 28 # Create a boolean mask for players older than 28
res_df = df_ext[mask] # Apply the mask to filter the DataFrame
res_df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0

In [12]:
df_ext.dropna(subset=["Name"], inplace=True) # Drop rows where 'Name' is NaN
#get all the players where Name starts with A and Salary is higher than the minimum
mask = (df_ext["Name"].str.startswith("A")) & (df_ext["Salary"] > df_ext["Salary"].min()) 


res_df = df_ext[mask] # Apply the mask to filter the DataFrame
print(f'There are {len(res_df)} players whose names start with A and have a salary higher than the minimum salary.')
res_df.head()

There are 34 players whose names start with A and have a salary higher than the minimum salary.

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0

In [13]:
df_ext.dropna(subset=["Name"], inplace=True) # Drop rows where 'Name' is NaN
#get all the players where Name starts with A or Salary is higher than the minimum
mask = (df_ext["Name"].str.startswith("A")) | (df_ext["Salary"] > df_ext["Salary"].min()) 


res_df = df_ext[mask] # Apply the mask to filter the DataFrame
print(f'There are {len(res_df)} players whose names start with A or have a salary higher than the minimum salary.')
res_df.head()

There are 447 players whose names start with A or have a salary higher than the minimum salary.

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0

In [14]:
df_ext["Name"].str.startswith("J"), df_ext["Salary"] > df_ext["Salary"].min() #Create two boolean series

(0      False
 1       True
 2       True
 3      False
 4       True
        ...
 452    False
 453    False
 454    False
 455    False
 456     True
 Name: Name, Length: 457, dtype: bool,
 0       True
 1       True
 2      False
 3       True
 4       True
        ...
 452     True
 453     True
 454     True
 455     True
 456     True
 Name: Salary, Length: 457, dtype: bool)

**`.at[]` and `.iat[]`**

In [15]:
df_ext.at[0,"Name"] # Access the 'Name' at index 0 using label-based scalar access

'Avery Bradley'

In [16]:
df_ext.iat[0, 0] # Access the entry at the first row and first column using integer-location based scalar access

'Avery Bradley'

### Series

In [17]:
series = pd.Series(list(df_ext["Salary"]), index=df_ext["Name"]) # Create a Series with 'Name' as index and 'Salary' as data
series

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
John Holland           NaN
R.J. Hunter      1148640.0
Jonas Jerebko    5000000.0
                   ...
Trey Lyles       2239800.0
Shelvin Mack     2433333.0
Raul Neto         900000.0
Tibor Pleiss     2900000.0
Jeff Withey       947276.0
Length: 457, dtype: float64

**Bracket `[]` Operator**

In [18]:
series["Avery Bradley"] # Access the salary of 'Avery Bradley' using the Series index

np.float64(7730337.0)

In [19]:
series[0]

/scratch/local/u1257442/845782/ipykernel_447834/878281628.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series[0]

np.float64(7730337.0)

**`loc[]` operator**

In [20]:
series.loc["Shelvin Mack":"Jeff Withey"] # Access salaries for players from 'Shelvin Mack' to 'Jeff Withey' using label-based indexing

Name
Shelvin Mack    2433333.0
Raul Neto        900000.0
Tibor Pleiss    2900000.0
Jeff Withey      947276.0
dtype: float64

In [21]:
series.iloc[0:2] # Access the first two entries in the Series using integer-location based indexing

Name
Avery Bradley    7730337.0
Jae Crowder      6796117.0
dtype: float64

### Boolean Indexing

In [22]:
#get all the records where salary is greater than 20000000
mask = series > 20000000

series[mask]

Name
Carmelo Anthony    22875000.0
Chris Paul         21468695.0
Kobe Bryant        25000000.0
Derrick Rose       20093064.0
LeBron James       22970500.0
Dwight Howard      22359364.0
Chris Bosh         22192730.0
Kevin Durant       20158622.0
dtype: float64

Next Chapter [Data Manipulation](4.DataManipulation.ipynb)