## Data Manipulation

1. **`df.drop()`:** Remove specified rows or columns from the DataFrame.

2. **`df.rename()`:** Rename columns or index labels.

3. **`df.sort_values()`:** Sort the DataFrame by specified columns.

4. **`df.groupby()`:** Group data based on one or more columns.

5. **`df.get_group()`:** Get a specific group from a grouped DataFrame using the group key.

6. **`df['a'].astype('data_type')`:** Convert the data type of a specific column 'a' to the specified data type.

7. **`df.set_index()`:** Set the DataFrame's index to a specific column.

8. **`df.reset_index()`:** Reset the DataFrame's index, optionally dropping the current index.

10. **`df.agg()`:** Perform aggregation operations on the DataFrame, like mean, sum, etc.

11. **`df.map()`:** Apply a function element-wise on a Series.

12. **`df.rank()`:** Compute numerical rank of elements in the DataFrame.

In [1]:
import pandas as pd
import numpy as np

In [2]:
#read the data
df = pd.read_csv("data/nba.csv") # Load NBA dataset into a DataFrame

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

**df.drop()**

In [3]:
df_new = df.drop(columns=["Height"], axis=1) # Drop the 'Height' column from the DataFrame
df_new.head()

,Name,Team,Number,Position,Age,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,231.0,NaN,5000000.0

**df.rename()**

In [4]:
#rename College to University and Salary to Wages -> column renaming
df_renamed = df.rename(columns= {"College":"University", "Salary":"Wages"})

df_renamed.head(3)

,Name,Team,Number,Position,Age,Height,Weight,University,Wages
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [5]:
#index renaming -> 0 and 1 to x and y
df_renamed = df.rename(index= {0:"x", 1:"y"})

df_renamed.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
x,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
y,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [6]:
#index -> map all index to string
df_renamed = df.rename(index = str)

df_renamed.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

**`sort_values()`**

In [7]:
#sort the values in by salary in descending and by name ascending
df_sorted = df.sort_values(by=["Salary", "Name"], ascending=[False, True])

df_sorted.head(8)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0

**`groupby()`**

In [8]:
#find mean of salary for each Team
df_grpd = df.groupby(by=["Team"], as_index=False)["Salary"].mean()

df_grpd.head(4)

                Team        Salary
0      Atlanta Hawks  4.860197e+06
1     Boston Celtics  4.181505e+06
2      Brooklyn Nets  3.501898e+06
3  Charlotte Hornets  5.222728e+06

In [9]:
#find avg, min, max and range of age of Age column for each team
df_grpd = df.groupby(by=["Team"], as_index=False).agg({"Age" : ["mean", "min", "max", lambda x : x.max()- x.min()]})
df_grpd.rename(columns={"<lambda_0>":"Range"}, inplace=True) # Rename the lambda column to 'Range'
df_grpd.head()

                Team        Age
                           mean   min   max Range
0      Atlanta Hawks  28.200000  22.0  35.0  13.0
1     Boston Celtics  24.733333  20.0  29.0   9.0
2      Brooklyn Nets  25.600000  21.0  32.0  11.0
3  Charlotte Hornets  26.133333  21.0  31.0  10.0
4      Chicago Bulls  27.400000  21.0  35.0  14.0

**`get_group`**

In [10]:
df_grpd = df.groupby("Team") # Group by 'Team' without resetting index
df_grpd.head() 
df_grpd.get_group('Atlanta Hawks')['Age'].mean() # Get the mean age for the 'Atlanta Hawks' team

np.float64(28.2)

**`df['a'].astype('data_type')`**

In [11]:
#convert salary to nearest integer
df["Salary"] = df["Salary"].fillna(0).astype('int64') # Convert 'Salary' column to integer, filling NaN with 0

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000

**`df.set_index()`**

In [12]:
#set Team as index

df_index = df.set_index(keys=["Team"])

df_index.head(4)

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337
Boston Celtics,Jae Crowder,99.0,SF,25.0,6-6,235.0,Marquette,6796117
Boston Celtics,John Holland,30.0,SG,27.0,6-5,205.0,Boston University,0
Boston Celtics,R.J. Hunter,28.0,SG,22.0,6-5,185.0,Georgia State,1148640

**`df.reset_index()`**

In [13]:
df_non_index = df_index.reset_index(level=None) # Reset index to default integer index
df_non_index.head(3)

,Team,Name,Number,Position,Age,Height,Weight,College,Salary
0,Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Boston Celtics,Jae Crowder,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,Boston Celtics,John Holland,30.0,SG,27.0,6-5,205.0,Boston University,0

**`df.agg()`**

In [14]:
#find avg age of the players

df["mean_age"] = df["Age"].fillna(0).agg("mean")

df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,mean_age
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337,26.879913
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117,26.879913
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,26.879913

**`df.map()`**

In [15]:
df["Position"] = df["Position"].map({"PG":"pg"}) # Map 'Position' values to lowercase abbreviations

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,mean_age
0,Avery Bradley,Boston Celtics,0.0,pg,25.0,6-2,180.0,Texas,7730337,26.879913
1,Jae Crowder,Boston Celtics,99.0,NaN,25.0,6-6,235.0,Marquette,6796117,26.879913
2,John Holland,Boston Celtics,30.0,NaN,27.0,6-5,205.0,Boston University,0,26.879913
3,R.J. Hunter,Boston Celtics,28.0,NaN,22.0,6-5,185.0,Georgia State,1148640,26.879913
4,Jonas Jerebko,Boston Celtics,8.0,NaN,29.0,6-10,231.0,NaN,5000000,26.879913

**`df.rank()`**

In [16]:
#add rank column for each team wrt Salary
df =df.dropna(subset=["Salary"]) # Drop rows with NaN in 'Salary' column to avoid issues during ranking
# Rank players within each team by 'Salary' in descending order
df["rank"] = df.groupby("Team")["Salary"].rank(ascending=False).astype('int64') # Convert rank to integer type

df.head(10) #The highest salary player in each team has rank 1

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

Next Chapter [Missing Data Handling](5.MissingDataHandling.ipynb)